### ISSUE TITLE
Resources tab - Instructions videos and pdfs

### ISSUE THREAD

**Issue by ghumman96** [OHSUCMP/coach#131]
Once everyone approves the videos, I will add them here to add to resources tab. Do they need to be posted on public YouTube to be played by participants?

**Comment by ghumman96** [comment]
Here are the materials for resources tab
**Control:**
[Video](https://youtu.be/m0751n7glxU)
Risks of Hypertension Study Results [Patient Welcome Packet Risk Text.pdf](https://github.com/OHSUCMP/coach/files/13826524/Patient.Welcome.Packet.Risk.Text.pdf)
COACH Participant FAQ [Participant FAQ sheet final.docx](https://github.com/OHSUCMP/coach/files/13826547/Participant.FAQ.sheet.final.docx)
COACH Written Instructions[COACH Instructions-Invite through EHR link.pdf](https://github.com/OHSUCMP/coach/files/13826565/COACH.Instructions-Invite.through.EHR.link.pdf)
OMRON Instructions [Syncing OMRON to COACH.pdf](https://github.com/OHSUCMP/coach/files/13826574/Syncing.OMRON.to.COACH.pdf)

**Intervention:**
[Video](https://youtu.be/AQGLdXV9ZTE)
Risks of Hypertension Study Results [Patient_Welcome Packet Risk text_clean- final.pdf](https://github.com/OHSUCMP/coach/files/13826535/Patient_Welcome.Packet.Risk.text_clean-.final.pdf)
COACH Participant FAQ [Participant FAQ sheet final.docx](https://github.com/OHSUCMP/coach/files/13826547/Participant.FAQ.sheet.final.docx)
COACH Written Instructions [COACH Instructions-Invite through EHR Link (2).pdf](https://github.com/OHSUCMP/coach/files/13826568/COACH.Instructions-Invite.through.EHR.Link.2.pdf)
OMRON Instructions [Syncing OMRON to COACH.pdf](https://github.com/OHSUCMP/coach/files/13826574/Syncing.OMRON.to.COACH.pdf)

**Comment by mattStorer** [comment]
@ghumman96 where precisely do we want these materials to display?  Do we want them all to appear on the Resources menu itself?  On the "Frequently Asked Questions" page?  Somewhere else?

![image](https://github.com/OHSUCMP/coach/assets/979938/62bc2be2-b585-4feb-896f-d8ab99ec752a)

**Comment by mattStorer** [comment]
got confirmation that the new links should appear in the menu, below _Side Effects to Report_ and above the divider linke

**Comment by mattStorer** [comment]
this is done.

updated Resources menu:
![image](https://github.com/OHSUCMP/coach/assets/979938/183668db-a79c-41a4-9fee-eb1fe0fb4682)

embedded video page:
![image](https://github.com/OHSUCMP/coach/assets/979938/1359c697-b075-4f76-accf-81d637fa0926)

embedded PDF page:
![image](https://github.com/OHSUCMP/coach/assets/979938/2f01a2f0-f7ab-467c-87f7-125ede65dced)

videos and PDFs grow and shrink in width based on window size.

because we store locally both _control_ and _intervention_ versions of PDFs, and we keep these in appropriately named folders in the _resources_ space -
![image](https://github.com/OHSUCMP/coach/assets/979938/c0b5d3b5-5c84-462d-99c8-fdfd1009faf3)

I've built this out to obfuscate these paths from the user, should they decide to dig into the page source for whatever reason (you can see that the folder structure outlined above is not represented in the link that the user might see if they examine page source):
![image](https://github.com/OHSUCMP/coach/assets/979938/0649f2d2-535f-45b3-9658-e81a28c81bfd)

also, by routing the serving of these assets through through _ResourcesController_ in this sort of obfuscated way, if a user attempts to retrieve assets while not authenticated, they're presented with an error message.  so that's cool.

tested out views for both _BASIC_ and _ENHANCED_ randomization groups, and I confirm the appropriate resources are loading as desired.

considering this issue resolved _except for_ some tweaks that I think should be made to the documents, which I'll outline in the next comment below.

**Comment by mattStorer** [comment]
@ghumman96 I think some updates may need to be made to the _COACH Written Instructions_ PDFs, just some things I noticed maybe we want to tweak this stuff before users get at it?

Weird lines documented in step 8 - I've highlighted them below here, not sure what they're all about?  Also the text looks like it's been photoshopped, was this image edited?  Users may see that and it could raise a flag to them that something's ... off.
![image](https://github.com/OHSUCMP/coach/assets/979938/a1cec3f9-7202-485f-997d-b1a78e9cf54a)

Resources tab - obviously this couldn't have been updated before with the stuff I just added, but I think we might want to try to recreate this image with the full Resources menu.  This image is also missing the "High Blood Pressure Control" header which should definitely be there.  I can help you with this since the new resources aren't deployed yet, but it seems this might want to get updated also.
![image](https://github.com/OHSUCMP/coach/assets/979938/6eca0831-825f-4b5c-a5c8-74962c900d2b)

Step 21 in the control document shows the dates from the chart that control users won't see, this shouldn't be there:
![image](https://github.com/OHSUCMP/coach/assets/979938/1784c697-5947-4914-93cd-98cb3718c434)

**Comment by mattStorer** [comment]
_COACH Written Instructions_ PDF documents updated to resolve various discrepancies and to add a bit of polish to the screenshots.  Standardized to a common fictitious _Kyle J_ user, same in both _intervention_ and _control_ groups.

with this edit, this ticket appears good to go, so closing.
