### ISSUE TITLE
ensure that only "current" hypotension adverse events make their way to the recommendation engine

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/coach#187]
presently, hypotension adverse events aren't being filtered when going to the recommendation engine to ensure that they're current (within the last month).  this needs to happen.  filtration logic should be added into _AdverseEventService.getAdverseEvents_ just before _hae_ is converted into an _AdverseEvent_ and added to the list, just before this line:

https://github.com/OHSUCMP/coach/blob/master/src/main/java/edu/ohsu/cmp/coach/service/AdverseEventService.java#L55

**Comment by mattStorer** [comment]
after additional communications, it sounds like we may be making more changes to this low BP logic to coincide more closely with high BP logic.  more discussions needed to nail down the precise details, TBD.

**Comment by aeyates** [comment]
Here is my understanding of how it should behave. We will need confirmation from @davedorr9.

First, check for 2 low BPs both within 14 days. If found:
1. Show a stop sign with the message that the BP is "still very low"
2. Is there an AE already recorded in COACH for this? If not, create one.
3. Send the AE (either newly created or already existing) to CQL.
4. Participant will get the recommendation either to contact their care team (if they have not indicated they've already done so) or to keep monitoring their AE (if they've said they talked to their care team)

If there are not 2 low BPs within 14 days, but the most recent BP is low (no matter how old):
1. Show a stop sign with the message that the BP is low.
2. Participant will get the recommendation to remeasure their BP because the last reading is low

As discussed on Thursday, this does not necessarily solve the problem for people who have low blood pressure all the time because their medication is working "too well". They could still get caught in a cycle of being told to contact their care team over and over again. To help limit this, there was a proposal to lower the diastolic threshold to 50 instead of 60.

**Comment by aeyates** [comment]
AE logic was previously only creating a Hypotension event if the two low BPs were HOME BPs. In order for logic to be consistent throughout the app, all BPs will be included in the logic.
