### ISSUE TITLE
Incorporate COACH logo

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#68]
Add the new COACH logo to the website. It should be in a consistent place, probably the top left corner:
https://www.tailorbrands.com/blog/logo-placement

**Comment by mattStorer** [comment]
we may want to construct a different logo - perhaps instead of white on dark blue, to be dark blue on white - so that the circle is visible on the dark blue bar of the app's header.

here's the logo: 
![image](https://github.com/OHSUCMP/coach/assets/979938/2cc37a2c-f4a0-4a00-974a-cd10e754d343)

here's the logo as it appears in the COACH menu bar at the top, scaled to a height that is small enough so that the bar itself doesn't need to increase in size to accommodate the logo:
![image](https://github.com/OHSUCMP/coach/assets/979938/bdb84587-0043-400d-898a-3abb39ee869c)

and here's what it looks like when the logo is scaled large enough to read, i.e. where the text is roughly the same size as the rest of the menu items:
![image](https://github.com/OHSUCMP/coach/assets/979938/2436daa8-7669-4456-af42-6251a45771b0)

clearly, the dark blue circle is the same color as the bar it's appearing on and so it disappears, which isn't useful at all.

**Comment by aeyates** [comment]
Aisha will be providing a new logo.

**Comment by mattStorer** [comment]
here's the new logo: 
<img width="185" alt="coach-logo" src="https://github.com/OHSUCMP/coach/assets/979938/b60d3f3e-0836-4352-a6d1-2c85a0e96f23">
