### ISSUE TITLE
Low BP Logic

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#81]
Logic for Low BP was mentioned in 8/29 meeting. Richelle was interested in it functioning like the High BP warning, queueing off a single reading. Possibly asking them to remeasure, although with low BP the first reading is generally more trusted. Finalize requirement and decide on definition of "low".

**Comment by davedorr9** [comment]
This is low priority but we can come back to it if there is time.

**Comment by aeyates** [comment]
More discussion in 9/26 meeting. Richelle says the low threshold is 90 and 60. Will suggested that it could work like high BP, where two in a row provides the recommendation to call the clinic. There was also discussion of describing symptoms like dizziness. So we'd need to finalize the text before proceeding. Richelle and Will consider this a higher priority for safety.

**Comment by davedorr9** [comment]
3 steps : 1 from Home BP entry page, automatically go to the Home page if BP < 90/60 ; 
2 if last BP within 30 days is < 90/60, new recommendation in AE workflow with the following text : 
New low blood pressure message (first low BP)
from David Dorr to everyone:    1:36 PM
Low blood pressure
from David Dorr to everyone:    1:37 PM
You recorded one blood pressure < 90/60 ; this is considered hypotension. Please remeasure your blood pressure in 5 to 15 minutes
from Michelle Bobo to everyone:    1:37 PM
https://www.heart.org/en/health-topics/high-blood-pressure/the-facts-about-high-blood-pressure/low-blood-pressure-when-blood-pressure-is-too-low

If last 2 BPs both < 90/60, should STORE condition as HYPOTENSION and then the CQF ruler should be fed that condition, triggering the AE workflow

**Comment by davedorr9** [comment]
NOTE : also move from HOME BP ENTRY PAGE AUTOMATICALLY TO HOME PAGE if BP => 180/120

**Comment by mattStorer** [comment]
notes from our meeting just now :

- if one BP entered and it's low, return to home screen and rerun recommendations.  AE workflow should trigger a card that instructs the user to take another reading.
- if two BPs entered and the first one is low, but the second one isn't, everything is fine; do not go to home page, do not rerun recommendations.
- if two BPs entered and the first one is normal, but the second one is low, return to home page and rerun recommendations.  AE workflow should trigger a card that instructs the user to take another reading.
- if two BPs entered and both are low, or in any other circumstance whereby the most recent two BPs entered are both low, go to the home page, and rerun recommendations, BUT FIRST we need to craft an AdverseEvent resource for Hypotension that represents these two low BP readings, which we are to persist in the COACH database.  this AE needs to be sent to CQF Ruler with other AEs.

I think that captures the workflow as it was discussed appropriately.

also, we will want to perform similar go-to-the-homepage-and-rerun-recommendations logic if the user enters critically-high BP readings, > 180/120.  however, it wasn't discussed if we are to craft Hypertension-oriented AEs, or if we want to persist any such resources in the COACH database.  In fact, the `adverse_event` table in the COACH database doesn't contain any references to hypertension AEs, so that is something we will want to clarify at some point.

**Comment by mattStorer** [comment]
can't just check vitals being entered into the UI, as there is no guarantee that the vitals being entered are going to have the most recent timestamp.  vitals can be entered with any timestamp.  as such, we basically need to get the two most recent BP readings after we create any.  if the most recent one is low, we need to rerun recommendations and bring the user back to the homepage.  however, we only want to ever do this once per most recent BP reading; that is, let's say they enter a low BP reading, and then enter several more with earlier timestamps, such that the most recent BP reading remains low, but there's only one of them.  those subsequent creates of historic BP readings should not trigger rerunning recommendations and bringing the user back to the home page each time; we've already done that the first time they entered the low BP reading.  does that make sense?  we need some way to track whether or not a BP reading has triggered a recommendation refresh, and to only ever do that once per BP entry.

**Comment by mattStorer** [comment]
we want to create an AdverseEvent if the two most recent BP readings are low.  what if the next reading taken after that is also low?  what if the user has 3 or 4, or 5 low readings in a row?  I think we will want to update the existing AE to reference all (most recent) (consecutive) low BP readings as being composite elements of that AE in it, to avoid creating multiple AEs that logically relate to the same event.

**Comment by mattStorer** [comment]
if a patient has multiple consecutive low BP readings, is there a time period by which we want to bound them with respect to delineating between different Adverse Events?  that is, let's say they have 5 consecutive low BP readings, but the first 3 occurred within a 24 hour period, but then they didn't take any BP readings for a week, and the very next time they took BP readings at all, a week later, the next two readings were also low?  technically, there are 5 consecutive low BP readings, and by certain logic they should all relate to the same event, but there was a week gap in the middle there.  does that make them two separate Adverse Events?

if this is the case, what sort of temporal bound do we want to enforce on the creation of such AdverseEvents, where all BP readings within a particular block are low?

does that make sense?

**Comment by mattStorer** [comment]
we've discussed persisting hypotension Adverse Events in the COACH database in order to pass these to the recommendation engine, but having put some thought into just how that would work and the complexity around it, as well as the inherently redundant nature of those events (i.e., those hypotension AEs would be based on hypotensive BP readings that we already have access to), I think it doesn't make sense to persist these AEs in the database at all.

instead, when we read in BPs when a user logs in, as we process those BPs, we craft hypotension AEs on the fly which we then keep in the user's workspace cache, in memory.

this is a much cleaner approach that negates all of the complexity and redundancy associated with attempting to persist these objects in the COACH database.

**Comment by mattStorer** [comment]
comments from Dave : 
- we definitely want to persist hypotension AEs in the database (so we don't want to craft them on the fly);
- each hypotension AE must consist of precisely two (2) low BP readings;
- the amount of time between consecutive low BP readings doesn't matter, all that matters is that they are consecutive

**Comment by mattStorer** [comment]
### developer notes re: handling BP readings created out of chronological order with respect to hypotension AEs -

we want each hypotension AE to be associated with two consecutive, low, home-BP readings.  no problem there.

but, since we permit BPs to be entered out of chronological order, it could be the case whereby a BP reading comes into the system that sits chronologically between two, otherwise-consecutive, low, home-BP readings, thereby retroactively rendering those two, otherwise-consecutive readings to be non-consecutive, and thereby negating the resultant AE.  in this case, we would probably want to simply delete the associated AE that no longer applies.

or, conversely, consider a case where there exists just one low, home-BP reading, surrounded by normal BP readings.  then, a new low home-BP reading comes in, that chronologically sits either directly before or directly after that existing low BP reading.  this would trigger the creation of a hypotension AE.  in this case, we would probably want to simply create the new AE that now applies to the two consecutive readings.

a weirder case to consider might be one whereby two low, home-BP readings A and B exist with an associated AE that references them (AB).  now a third low, home-BP reading C is recorded that sits chronologically before or between these two (i.e. order CAB or ACB).  if the AE must reference precisely two consecutive low BP readings, then this insertion could create a case whereby the AE should be updated to reference low BP readings CA or AC, depending on where C is placed in the timeline.  I suppose in this case the AE would need to be updated to reference the first two consecutive low BP readings.

there's all sorts of weirdness that could occur as a result of these edge cases.

the logic with respect to how to process these non-chronological insertions makes sense and isn't particularly complicated, but it does create some additional processing around them to ensure that things line up appropriately and don't get out of whack.

**Comment by mattStorer** [comment]
### developer notes -

"home" BP readings may exist only in the context of the remote server, i.e. coming from an Epic flowsheet or elsewhere, such that we do not have a local copy of the BP reading in the COACH database.

this can complicate matters with respect to the current strategy of having a hypotension AE reference the constituent BP readings directly (i.e. by their `id` value in the `home_bp_reading` table).

I think we probably need to store hypotension AE resources with their values only, and not make attempts to link them to their constituent records.

**Comment by mattStorer** [comment]
pretty much everything built out, except for the redirect-to-homepage-on-low-bp-entry bit.  that should be quick though and just involves some UI work.  once that's sorted, will want to vet logic with the team and adjust as needed.

**Comment by mattStorer** [comment]
I believe all logic for this is completed.  we should review its logic to confirm.  also if there are any updates that may need to be made to the recommendation logic, that will still need to be implemented (something @aeyates will probably need to handle).  keeping this ticket open until we've confirmed desired behavior.

**Comment by mattStorer** [comment]
> As long as the adverse event comes across with the 'coach-adverse-event' coding, I would treat them all the same.

this is the case, for sure.  see https://github.com/OHSUCMP/coach/blob/master/src/main/java/edu/ohsu/cmp/coach/service/AdverseEventService.java#L131-L166 for details on how the new AE is constructed.  (it has already been shown to integrate with existing AE workflow operation, including card generation, user interaction, outcomes, etc.

> The new AE workflow hasn't been written yet and is supposed to involve REDCap. I don't feel like we've nailed down those requirements yet, but I'm not sure how this would be any different.

yeah, it sounds like LeAnn is aiming to nail down the REDCap forms in the next couple days.  and based on discussions in today's meeting, we will probably need to leverage REDCap to collect AEs, as the COACH database is deidentified, and so we won't be able to generate meaningful reports from it.

**Comment by aeyates** [comment]
The following has not been implemented yet:
- Recommendation changes
- Graph display changes

Questions:
1. Should the low BP recommendations show for both control and intervention? I think the answer is yes, and if so we can't throw the single low BP recommendation under "monitoring" as given in the screenshot (https://ohsuitg-my.sharepoint.com/:p:/r/personal/dunnem_ohsu_edu/Documents/From_Box/COACH%20High%20Blood%20Pressure/Phase2COACH/Mockups%20and%20Screenshots/Cases%20Mockups/High%20and%20Low%20BP%20options.pptx?d=we752f2760c834c66aef2b3367a5662fc&csf=1&web=1&e=Q4Z2cc). We either need to co-opt one of the workflows we always show (e.g. Hypertensive Emergency) or add a new one.
2. Are there any time limits around low BP readings? Do they need to be within the last 14 days like High BP readings? I think from what I've read above the answer is no, but want verification.

**Comment by aeyates** [comment]
I've implemented the "Hypertensive Emergency" recommendation to fire for a single low BP. I've renamed the recommendation "Blood Pressure Warning" (removing the word 'High'). This is what will fire whenever either low or high BPs are detected, and control and intervention will get these. There is no time constraint for low BP. If the most recent 2 are low, the Hypertensive Emergency recommendation will return nothing, but COACH creates an adverse event which will trigger that recommendation instead. Screenshots:

<img width="1622" alt="Screen Shot 2023-10-24 at 3 32 51 PM" src="https://github.com/OHSUCMP/coach/assets/2576491/c45aa94a-fcd0-4f86-aa01-4f73b0cfa5e8">

<img width="1622" alt="Screen Shot 2023-10-24 at 3 33 47 PM" src="https://github.com/OHSUCMP/coach/assets/2576491/034fb6eb-33a8-4519-b2b4-30f8a9659275">
