### ISSUE TITLE
Language for preset goal

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/coach#86]
When a goal has been automatically set, the participant should receive a message below the goal on the home page to let them know that they should work with their care team to set an appropriate goal. This message should be dismissable and never show again.

Need language, proposal is to put the language under the goal

**Comment by ghumman96** [comment]
140/90 is default. Update you BP goal only if you've discussed different goal with your care team.  Can use the same language for the goal setting tab.

**Comment by davedorr9** [comment]
On the home page (hover)
140/90 is default. Update your BP goal only if you've discussed a different goal with your care team. 
On the goal entry page:
Update your BP goal only if you've discussed a different goal with your care team.

**Comment by aeyates** [comment]
I've updated the language on the goal entry page. Updating on the home page will take additional effort to track that the goal was created as a default, requiring a db schema change. @mattStorer Do you have thoughts on this? The goal table is generic, so it's awkward to add a column to track this one-off thing for BP Goals. But persistence is the only way to know we have to show this special text in some cases.

**Comment by mattStorer** [comment]
@aeyates hmm yeah that would be kinda awkward and dumb, but I don't know how else to do it.  let me think about it a bit

**Comment by mattStorer** [comment]
so, a default BP goal is set here, in the event that no EHR BP goal exists, and no BP goal exists in the COACH database:

https://github.com/OHSUCMP/coach/blob/master/src/main/java/edu/ohsu/cmp/coach/service/GoalService.java#L114-L117

The code above creates a new `MyGoal` _entity_ object, which is persisted, using this constructor:

https://github.com/OHSUCMP/coach/blob/master/src/main/java/edu/ohsu/cmp/coach/entity/MyGoal.java#L45-L53

IDEA - it's a little hacky, but perhaps less hacky than creating an entirely separate column in the _goal_ table to store a "this is the default BP goal" concept -

What if we were to create a new `MyGoal` constructor, or add a parameter to the existing one, that says "hey, this is a default," which then just _modifies_ the `goalText` field to append "(default)" to read "Target BP: x/y (default)"?  Or something like that?  Something in the text field that indicates the BP goal is a default.

We don't use the `goalText` field for BP goals - we use the `systolicTarget` and `diastolicTarget` fields - so the `goalText` field is rather extraneous on BP goals.  We use it on _other_ goals, but not _BP_ goals.  So if we were to tweak that text, and then just look for that text, we could achieve the same result.

Perhaps also add a `public static final String DEFAULT_BP_GOAL_SUFFIX = "(default)"` that we could then match against in other code so that text is nicely centralized and stuff.

Does that make sense?

Thoughts, @aeyates ?  @ghumman96 ?

**Comment by mattStorer** [comment]
Alternatively, we could create a separate `extGoalId` field, which is normally "bp-goal" and defined by `GoalModel.BP_GOAL_ID` :

https://github.com/OHSUCMP/coach/blob/master/src/main/java/edu/ohsu/cmp/coach/model/GoalModel.java#L16

We could create a new `GoalModel.DEFAULT_BP_GOAL_ID` field (with value "default-bp-goal" for example), and then set that on the default BP goal in the table.

This would also work, **BUT** doing so would necessitate matching against `DEFAULT_BP_GOAL_ID` anywhere the system already matches against `BP_GOAL_ID` to ensure that default BP goals are considered when non-default BP goals are considered.  Might be cleaner to do it this way than to do text matching, at the risk of potentially introducing bugs if we don't catch all the places it's used.

Thoughts?

**Comment by aeyates** [comment]
I guess the question is whether the hackiness is worth it. Is this feature really important? @ghumman96  This is all to simply tell someone that their goal was set by default and that they can change it with their care team. We do have language on the goal setting page warning them not to change it without consulting the care team. Maybe this is enough?

<img width="695" alt="Screen Shot 2023-12-19 at 3 22 51 PM" src="https://github.com/OHSUCMP/coach/assets/2576491/3aadfd13-fbab-4201-901d-7ddfa9e92ea6">

**Comment by davedorr9** [comment]
A few thoughts : one, just have a flag that is changed when the BP goal is changed. This process could include  : reading a goal from the order (if no goal included, then don't set the flag); or if someone changes the goal on the page. (e.g., a single line to change the flag GOAL_CHANGED = 1 instead of 0. IF GOAL_CHANGED=1, then don't show the hover above; otherwise show it.
GOAL_CHANGED = 0 would be default on every patient. 
If this is too much work, then okay to leave the new text. We will want to extract the current BP Goal for analysis, so glad you are storing that.

**Comment by mattStorer** [comment]
we could establish such a flag _bpGoalChanged_ in the _patient_ table, defaulted to `false`.  it would be set to `true` if a BP goal is read in from an _Order_, or if the user changes their goal manually.

Another way to say this is that _bpGoalChanged_ would only ever remain `false` if no BP goal has been configured in any external systems, such that COACH generates a default BP goal for the user.

**Questions:**
- would we want to set _bpGoalChanged_=`true` if the user has a Goal configured in Epic?  Goals can come from there as well.  (presumably we would want this)
- is there any circumstance when we might want to set _bpGoalChanged_=`false`?  to revert that flag back?  (presumably we would not)

**Comment by aeyates** [comment]
Discussed in 12/21 meeting. or analysis purposes, it will be important to know whether a person's BP goal was automatically set or not, so this information should be persisted no matter what solution is chosen.

**Comment by mattStorer** [comment]
this should be completed for now, with the caveat that we will need to update logic when we can successfully retrieve a BP goal from a ServiceRequest Order to ensure those such goals are considered as well.

established a new `boolean` _bpGoalUpdated_ in the _patient_ table (default `false`).  the Flyway schema migration will check against the _goal_ table to see if the associated _patient_ record has any 'bp-goal' records with a _systolicTarget_ that is not `140` and a _diastolicTarget_ that is not `90`.  in the presence of such 'bp-goal' records, _bpGoalUpdated_ becomes `true`.

thereafter, _bpGoalUpdated_ can only become `true` if:
- the user has any BP goal _Goal_ resources that come into COACH from the FHIR server; or
- the user manually changes their BP goal on the _Goals_ page in COACH.

the take-away is that COACH will retain whether or not the user has modified their BP goal or has any externally-defined BP goal in the source FHIR server.  this flag will remain set whether or not the user reverts back to the default BP goal.

as for the hover tooltip on the home page, this will display whenever the user's BP goal is the default of 140/90, as specified in the requirements above.  it does not take into account whether or not the user has changed their goal at any time in the past, so it has not relationship to the new _bpGoalUpdated_ flag.  if the tooltip should be based off the _bpGoalUpdated_ flag instead, this will be a very easy change to make so just let me know if that's what we want.

pushed to develop and considering resolved.

**Comment by aeyates** [comment]
@mattStorer The point of storing the information is to display the hover text appropriately - that is, to only display it if the user receives a default goal set by COACH, so it should be linked to the new variable.

**Comment by mattStorer** [comment]
@aeyates okay sounds good.  I *thought* that was probably the case, but that's also not what was written.  my understanding of the new boolean _bpGoalUpdated_ is that it also serves the purpose from a post-study analytics perspective to answer the question, "did the user change their BP goal?".  _bpGoalUpdated_ could serve that purpose and not be related to display of the tooltip, although it does make sense that they're probably related as they're both referenced on the same issue.

anyhow, I've updated the codebase to show the tooltip only if _bpGoalUpdated_ is false.
