### ISSUE TITLE
Written BPs coming back to COACH as Office BPs on graph

### ISSUE THREAD

**Issue by davedorr9** [OHSUCMP/coach#97]
For Andrew FHIR in POC, a set of BPs recorded in COACH that were written back to Epic as part of the interface now show up a few days later as 'office BPs' (e.g., the marker is a circle versus a square)

**Comment by mattStorer** [comment]
got a chance to dig into this a bit.  looks like the issue is that somewhere along the line, things got flipped with respect to home vs office icons.  this screenshot illustrates the issue, where "Home BP" is shown as a square, but the generating logic makes all Home BP readings circles (and vice versa).

![image](https://github.com/OHSUCMP/coach/assets/979938/51e9113d-6f42-4722-823d-383958844f34)

should be pretty trivial to fix this.

**Comment by mattStorer** [comment]
this is fixed and on POC
