### ISSUE TITLE
Change patient sex references to gender

### ISSUE THREAD

**Issue by MichelleBobo** [OHSUCMP/coach#98]
Ensure inclusive language by changing patient sex to gender in top banner and anywhere else.

**Comment by mattStorer** [comment]
@MichelleBobo we've been using patient gender since February 2022.  if a patient has the "gender extension" attached to their resource, we use what's stored there, otherwise there are fallback strategies in place to use sex.

`GENDER_EXTENSION_URL = "http://hl7.org/fhir/StructureDefinition/patient-genderIdentity";`

here's the logic that sets it.  it basically says that if a patient has the gender extension on their resource, we use it's `display` value if one exists.  if a `display` value doesn't exist, but its `code` exists, we use the `code` value for their gender.  if neither of those exist, but the extension has a `text` value, we use that.  if none of that exists at all, we grab their gender from their  `gender` element (not from the extension).

```
        if (p.hasExtension(GENDER_EXTENSION_URL)) {
            logger.debug("gender-identity extension found for Patient with id=" + id);

            Extension ext = p.getExtensionByUrl(GENDER_EXTENSION_URL);
            CodeableConcept cc = (CodeableConcept) ext.getValue();
            if (cc.hasCoding()) {
                Coding c = cc.getCodingFirstRep();

                if (c.hasDisplay()) {
                    logger.debug("setting gender=" + c.getDisplay() + " from extension Coding.display for Patient with id=" + id);
                    gender = c.getDisplay();

                } else if (c.hasCode()) {
                    logger.debug("setting gender=" + c.getCode() + " from extension Coding.code for Patient with id=" + id);
                    gender = c.getCode();
                }
            }

            if (gender == null && cc.hasText()) {
                logger.debug("setting gender=" + cc.getText() + " from extension CodeableConcept.text for Patient with id=" + id);
                gender = cc.getText();
            }
        }

        if (gender == null && p.hasGender()) {
            gender = p.getGender().getDisplay();
        }
```

if you are seeing a patient in COACH that is showing an incorrect gender, it's most likely because their gender isn't set on their record.

are you working with a POC patient?  if so, who?

**Comment by MichelleBobo** [comment]
Reviewed with team, no work needed at this time unless issues pop up with Missouri or Vanderbilt.
